-- Seed data for psi-manager-backend (MySQL 8)
SET NAMES utf8mb4;
SET time_zone = '+00:00';

-- Permissions catalog
INSERT INTO permissions (code, module, name, description) VALUES
  ('agenda.read', 'agenda', 'Agenda read', 'View appointments'),
  ('agenda.write', 'agenda', 'Agenda write', 'Create and edit appointments'),
  ('patients.read', 'patients', 'Patients read', 'View patients'),
  ('patients.write', 'patients', 'Patients write', 'Create and edit patients'),
  ('services.read', 'services', 'Services read', 'View services'),
  ('services.write', 'services', 'Services write', 'Create and edit services'),
  ('packages.read', 'packages', 'Packages read', 'View packages'),
  ('packages.write', 'packages', 'Packages write', 'Create and edit packages'),
  ('clinical_tools.read', 'clinical_tools', 'Clinical tools read', 'View clinical tools'),
  ('clinical_tools.write', 'clinical_tools', 'Clinical tools write', 'Create and edit clinical tools'),
  ('pei.read', 'pei', 'PEI read', 'View neuro/PEI module'),
  ('pei.write', 'pei', 'PEI write', 'Create and edit neuro/PEI data'),
  ('records.read', 'records', 'Records read', 'View medical records'),
  ('records.write', 'records', 'Records write', 'Create and edit medical records'),
  ('forms.read', 'forms', 'Forms read', 'View clinical forms'),
  ('forms.write', 'forms', 'Forms write', 'Create and edit clinical forms'),
  ('documents.read', 'documents', 'Documents read', 'View documents'),
  ('documents.write', 'documents', 'Documents write', 'Upload and edit documents'),
  ('products.read', 'products', 'Products read', 'View products'),
  ('products.write', 'products', 'Products write', 'Create and edit products'),
  ('payments.read', 'payments', 'Payments read', 'View payments'),
  ('payments.write', 'payments', 'Payments write', 'Create and edit payments'),
  ('comandas.read', 'comandas', 'Comandas read', 'View comandas'),
  ('comandas.write', 'comandas', 'Comandas write', 'Create and edit comandas'),
  ('permissions.read', 'permissions', 'Permissions read', 'View permissions'),
  ('permissions.write', 'permissions', 'Permissions write', 'Edit permissions')
ON DUPLICATE KEY UPDATE
  module = VALUES(module),
  name = VALUES(name),
  description = VALUES(description);

-- Role permissions (basic defaults)
INSERT INTO role_permissions (role, permission_code) VALUES
  ('super_admin', 'agenda.read'),
  ('super_admin', 'agenda.write'),
  ('super_admin', 'patients.read'),
  ('super_admin', 'patients.write'),
  ('super_admin', 'services.read'),
  ('super_admin', 'services.write'),
  ('super_admin', 'packages.read'),
  ('super_admin', 'packages.write'),
  ('super_admin', 'clinical_tools.read'),
  ('super_admin', 'clinical_tools.write'),
  ('super_admin', 'pei.read'),
  ('super_admin', 'pei.write'),
  ('super_admin', 'records.read'),
  ('super_admin', 'records.write'),
  ('super_admin', 'forms.read'),
  ('super_admin', 'forms.write'),
  ('super_admin', 'documents.read'),
  ('super_admin', 'documents.write'),
  ('super_admin', 'products.read'),
  ('super_admin', 'products.write'),
  ('super_admin', 'payments.read'),
  ('super_admin', 'payments.write'),
  ('super_admin', 'comandas.read'),
  ('super_admin', 'comandas.write'),
  ('super_admin', 'permissions.read'),
  ('super_admin', 'permissions.write'),

  ('admin', 'agenda.read'),
  ('admin', 'agenda.write'),
  ('admin', 'patients.read'),
  ('admin', 'patients.write'),
  ('admin', 'services.read'),
  ('admin', 'services.write'),
  ('admin', 'packages.read'),
  ('admin', 'packages.write'),
  ('admin', 'clinical_tools.read'),
  ('admin', 'clinical_tools.write'),
  ('admin', 'pei.read'),
  ('admin', 'pei.write'),
  ('admin', 'records.read'),
  ('admin', 'records.write'),
  ('admin', 'forms.read'),
  ('admin', 'forms.write'),
  ('admin', 'documents.read'),
  ('admin', 'documents.write'),
  ('admin', 'products.read'),
  ('admin', 'products.write'),
  ('admin', 'payments.read'),
  ('admin', 'payments.write'),
  ('admin', 'comandas.read'),
  ('admin', 'comandas.write'),
  ('admin', 'permissions.read'),
  ('admin', 'permissions.write'),

  ('profissional', 'agenda.read'),
  ('profissional', 'agenda.write'),
  ('profissional', 'patients.read'),
  ('profissional', 'patients.write'),
  ('profissional', 'clinical_tools.read'),
  ('profissional', 'clinical_tools.write'),
  ('profissional', 'pei.read'),
  ('profissional', 'pei.write'),
  ('profissional', 'records.read'),
  ('profissional', 'records.write'),
  ('profissional', 'forms.read'),
  ('profissional', 'forms.write'),
  ('profissional', 'documents.read'),

  ('secretario', 'agenda.read'),
  ('secretario', 'agenda.write'),
  ('secretario', 'patients.read'),
  ('secretario', 'patients.write'),
  ('secretario', 'services.read'),
  ('secretario', 'packages.read'),
  ('secretario', 'payments.read'),
  ('secretario', 'comandas.read')
ON DUPLICATE KEY UPDATE role = VALUES(role), permission_code = VALUES(permission_code);

-- Super admin user (set password_hash to a valid bcrypt before using)
INSERT INTO users (tenant_id, role, name, email, password_hash, is_active)
VALUES (NULL, 'super_admin', 'Super Admin', 'admin@psipainel.com.br', '$2b$10$KUdLQ6BeTbx1imBZPsrbnuuUIFz3A5xMYkdC35Vpv7RmniDQTnKCy', 1)
ON DUPLICATE KEY UPDATE
  role = VALUES(role),
  name = VALUES(name),
  password_hash = VALUES(password_hash),
  is_active = VALUES(is_active);
